
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("0ed3e708-77c1-4458-8e4e-82e114ed127f")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class FutureShop
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new FutureShop object using the connection string found in the 'FutureShop' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=FutureShop", "FutureShop")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new FutureShop object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "FutureShop")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new FutureShop object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "FutureShop")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MSTDEVICEs() As ObjectSet(Of MSTDEVICE)
        Get
            If (_MSTDEVICEs Is Nothing) Then
                _MSTDEVICEs = MyBase.CreateObjectSet(Of MSTDEVICE)("MSTDEVICEs")
            End If
            Return _MSTDEVICEs
        End Get
    End Property

    Private _MSTDEVICEs As ObjectSet(Of MSTDEVICE)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MSTDEVKBNs() As ObjectSet(Of MSTDEVKBN)
        Get
            If (_MSTDEVKBNs Is Nothing) Then
                _MSTDEVKBNs = MyBase.CreateObjectSet(Of MSTDEVKBN)("MSTDEVKBNs")
            End If
            Return _MSTDEVKBNs
        End Get
    End Property

    Private _MSTDEVKBNs As ObjectSet(Of MSTDEVKBN)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MSTDEVTYPEs() As ObjectSet(Of MSTDEVTYPE)
        Get
            If (_MSTDEVTYPEs Is Nothing) Then
                _MSTDEVTYPEs = MyBase.CreateObjectSet(Of MSTDEVTYPE)("MSTDEVTYPEs")
            End If
            Return _MSTDEVTYPEs
        End Get
    End Property

    Private _MSTDEVTYPEs As ObjectSet(Of MSTDEVTYPE)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MSTDEVICEs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMSTDEVICEs(ByVal mSTDEVICE As MSTDEVICE)
        MyBase.AddObject("MSTDEVICEs", mSTDEVICE)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MSTDEVKBNs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMSTDEVKBNs(ByVal mSTDEVKBN As MSTDEVKBN)
        MyBase.AddObject("MSTDEVKBNs", mSTDEVKBN)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MSTDEVTYPEs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMSTDEVTYPEs(ByVal mSTDEVTYPE As MSTDEVTYPE)
        MyBase.AddObject("MSTDEVTYPEs", mSTDEVTYPE)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FutureEntities", Name:="MSTDEVICE")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MSTDEVICE
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MSTDEVICE object.
    ''' </summary>
    ''' <param name="dEV_MNG_NO">Initial value of the DEV_MNG_NO property.</param>
    ''' <param name="dEV_NO">Initial value of the DEV_NO property.</param>
    Public Shared Function CreateMSTDEVICE(dEV_MNG_NO As Global.System.Int64, dEV_NO As Global.System.String) As MSTDEVICE
        Dim mSTDEVICE as MSTDEVICE = New MSTDEVICE
        mSTDEVICE.DEV_MNG_NO = dEV_MNG_NO
        mSTDEVICE.DEV_NO = dEV_NO
        Return mSTDEVICE
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DEV_MNG_NO() As Global.System.Int64
        Get
            Return _DEV_MNG_NO
        End Get
        Set
            If (_DEV_MNG_NO <> Value) Then
                OnDEV_MNG_NOChanging(value)
                ReportPropertyChanging("DEV_MNG_NO")
                _DEV_MNG_NO = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("DEV_MNG_NO")
                OnDEV_MNG_NOChanged()
            End If
        End Set
    End Property

    Private _DEV_MNG_NO As Global.System.Int64
    Private Partial Sub OnDEV_MNG_NOChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnDEV_MNG_NOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DEV_NO() As Global.System.String
        Get
            Return _DEV_NO
        End Get
        Set
            OnDEV_NOChanging(value)
            ReportPropertyChanging("DEV_NO")
            _DEV_NO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("DEV_NO")
            OnDEV_NOChanged()
        End Set
    End Property

    Private _DEV_NO As Global.System.String
    Private Partial Sub OnDEV_NOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDEV_NOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DEV_NAME() As Global.System.String
        Get
            Return _DEV_NAME
        End Get
        Set
            OnDEV_NAMEChanging(value)
            ReportPropertyChanging("DEV_NAME")
            _DEV_NAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DEV_NAME")
            OnDEV_NAMEChanged()
        End Set
    End Property

    Private _DEV_NAME As Global.System.String
    Private Partial Sub OnDEV_NAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDEV_NAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DEV_IMAGE() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_DEV_IMAGE)
        End Get
        Set
            OnDEV_IMAGEChanging(value)
            ReportPropertyChanging("DEV_IMAGE")
            _DEV_IMAGE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DEV_IMAGE")
            OnDEV_IMAGEChanged()
        End Set
    End Property

    Private _DEV_IMAGE As Global.System.Byte()
    Private Partial Sub OnDEV_IMAGEChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnDEV_IMAGEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PRICE() As Global.System.String
        Get
            Return _PRICE
        End Get
        Set
            OnPRICEChanging(value)
            ReportPropertyChanging("PRICE")
            _PRICE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PRICE")
            OnPRICEChanged()
        End Set
    End Property

    Private _PRICE As Global.System.String
    Private Partial Sub OnPRICEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPRICEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DEV_TYPE() As Nullable(Of Global.System.Int32)
        Get
            Return _DEV_TYPE
        End Get
        Set
            OnDEV_TYPEChanging(value)
            ReportPropertyChanging("DEV_TYPE")
            _DEV_TYPE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DEV_TYPE")
            OnDEV_TYPEChanged()
        End Set
    End Property

    Private _DEV_TYPE As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDEV_TYPEChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDEV_TYPEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MODEL() As Nullable(Of Global.System.Int32)
        Get
            Return _MODEL
        End Get
        Set
            OnMODELChanging(value)
            ReportPropertyChanging("MODEL")
            _MODEL = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MODEL")
            OnMODELChanged()
        End Set
    End Property

    Private _MODEL As Nullable(Of Global.System.Int32)
    Private Partial Sub OnMODELChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnMODELChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DEV_KBN() As Nullable(Of Global.System.Int32)
        Get
            Return _DEV_KBN
        End Get
        Set
            OnDEV_KBNChanging(value)
            ReportPropertyChanging("DEV_KBN")
            _DEV_KBN = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DEV_KBN")
            OnDEV_KBNChanged()
        End Set
    End Property

    Private _DEV_KBN As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDEV_KBNChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDEV_KBNChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FutureEntities", Name:="MSTDEVKBN")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MSTDEVKBN
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MSTDEVKBN object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="dEVTYPEID">Initial value of the DEVTYPEID property.</param>
    ''' <param name="dEVTYPEKBN">Initial value of the DEVTYPEKBN property.</param>
    Public Shared Function CreateMSTDEVKBN(id As Global.System.Int32, dEVTYPEID As Global.System.Int32, dEVTYPEKBN As Global.System.Int32) As MSTDEVKBN
        Dim mSTDEVKBN as MSTDEVKBN = New MSTDEVKBN
        mSTDEVKBN.ID = id
        mSTDEVKBN.DEVTYPEID = dEVTYPEID
        mSTDEVKBN.DEVTYPEKBN = dEVTYPEKBN
        Return mSTDEVKBN
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NAME() As Global.System.String
        Get
            Return _NAME
        End Get
        Set
            OnNAMEChanging(value)
            ReportPropertyChanging("NAME")
            _NAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NAME")
            OnNAMEChanged()
        End Set
    End Property

    Private _NAME As Global.System.String
    Private Partial Sub OnNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DEVTYPEID() As Global.System.Int32
        Get
            Return _DEVTYPEID
        End Get
        Set
            OnDEVTYPEIDChanging(value)
            ReportPropertyChanging("DEVTYPEID")
            _DEVTYPEID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DEVTYPEID")
            OnDEVTYPEIDChanged()
        End Set
    End Property

    Private _DEVTYPEID As Global.System.Int32
    Private Partial Sub OnDEVTYPEIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDEVTYPEIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DEVTYPEKBN() As Global.System.Int32
        Get
            Return _DEVTYPEKBN
        End Get
        Set
            OnDEVTYPEKBNChanging(value)
            ReportPropertyChanging("DEVTYPEKBN")
            _DEVTYPEKBN = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DEVTYPEKBN")
            OnDEVTYPEKBNChanged()
        End Set
    End Property

    Private _DEVTYPEKBN As Global.System.Int32
    Private Partial Sub OnDEVTYPEKBNChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDEVTYPEKBNChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="FutureEntities", Name:="MSTDEVTYPE")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MSTDEVTYPE
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MSTDEVTYPE object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreateMSTDEVTYPE(id As Global.System.Int32) As MSTDEVTYPE
        Dim mSTDEVTYPE as MSTDEVTYPE = New MSTDEVTYPE
        mSTDEVTYPE.ID = id
        Return mSTDEVTYPE
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NAME() As Global.System.String
        Get
            Return _NAME
        End Get
        Set
            OnNAMEChanging(value)
            ReportPropertyChanging("NAME")
            _NAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NAME")
            OnNAMEChanged()
        End Set
    End Property

    Private _NAME As Global.System.String
    Private Partial Sub OnNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNAMEChanged()
    End Sub

    #End Region

End Class

#End Region


